import { makeStyles } from 'tss-react/mui';

const useStyles = makeStyles()((theme) => ({
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
    width: '100%',
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 12,
    paddingBottom: 12,
    position: 'relative',
    background:
      'radial-gradient(58.52% 100% at 0% 0%, rgba(177, 252, 3, 0.47) 0%, rgba(177, 252, 3, 0.14) 100%)',
    backdropFilter: 'blur(4px)',
  },
  title: {
    color: theme.palette.mode === 'light' ? '#000' : '#FFF',
    fontSize: 14,
    fontWeight: 600,
    lineHeight: '165%',
    fontFamily: 'var(--font-figtree), "Figtree", sans-serif',
    fontStyle: 'normal',
    margin: 0,
    paddingRight: 16,
  },
  description: {
    color: theme.palette.mode === 'light' ? '#000' : '#BBB',
    fontSize: 14,
    fontWeight: 400,
    lineHeight: '20px',
    letterSpacing: '-0.14px',
    fontFamily: 'var(--font-figtree), "Figtree", sans-serif',
    fontStyle: 'normal',
    margin: 0,
    '& a': {
      color: theme.palette.mode === 'light' ? '#000' : '#B1FC03',
      fontWeight: 500,
      fontSize: 14,
      lineHeight: '20px',
      letterSpacing: '-0.14px',
      fontFamily: 'var(--font-figtree), "Figtree", sans-serif',
      fontStyle: 'normal',
      textDecorationLine: 'underline',
      textDecorationStyle: 'solid',
      textDecorationSkipInk: 'auto',
      textDecorationThickness: 'auto',
      textUnderlineOffset: 'auto',
      textUnderlinePosition: 'from-font',
      '&:hover': {
        opacity: 0.8,
      },
    },
    '& .highlight': {
      color: theme.palette.mode === 'light' ? '#000' : '#FFF',
      fontWeight: 500,
      fontSize: 14,
      lineHeight: '20px',
      letterSpacing: '-0.14px',
      fontFamily: 'var(--font-figtree), "Figtree", sans-serif',
      fontStyle: 'normal',
    },
  },
  closeButton: {
    position: 'absolute',
    padding: 4,
    top: 12,
    right: 12,
    cursor: 'pointer',
    background: 'transparent',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '&:hover': {
      opacity: 0.5,
    },
  },
}));

export default useStyles;
