name: Docker-Production

on:
  push:
    branches:
      - master

env:
  REPO: big-dipper-ui
  ORG: coreumfoundation
  DEVNET_WEBHOOK_ENDPOINT: https://keel.devnet-1.coreum.dev/v1/webhooks/native
  TESTNET_WEBHOOK_ENDPOINT: https://keel.testnet-1.coreum.dev/v1/webhooks/native
  MAINNET_WEBHOOK_ENDPOINT: https://keel.mainnet-1.coreum.dev/v1/webhooks/native

jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Env
        run: |
          echo "TAG=`ruby -e 'puts File.read("apps/web-coreum/package.json").match(/"version": "(?<semver>(0|[1-9][0-9]*).(0|[1-9][0-9]*).(0|[1-9][0-9]*)-(0|[1-9][0-9]*))"/)[:semver]'`" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.ORG }}/${{ env.REPO }}:${{ env.TAG }}
            ${{ env.ORG }}/${{ env.REPO }}:latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          push: true
          build-args: |
            PROJECT_NAME=web-coreum
            VERSION=${{ env.TAG }}

      - name: Update Devnet Deployment
        run: |-
          curl -v -u "${{ secrets.KEEL_DEVNET_USERNAME }}:${{ secrets.KEEL_DEVNET_PASSWORD }}" -X POST ${{ env.DEVNET_WEBHOOK_ENDPOINT }}  -H "Content-Type: application/json" -d "{\"name\": \"${{ env.ORG }}/${{ env.REPO }}\", \"tag\": \"${{ env.TAG }}\"}"

      - name: Update Testnet Deployment
        run: |-
          curl -v -u "${{ secrets.KEEL_TESTNET_USERNAME }}:${{ secrets.KEEL_TESTNET_PASSWORD }}" -X POST ${{ env.TESTNET_WEBHOOK_ENDPOINT }} -H "Content-Type: application/json" -d "{\"name\": \"${{ env.ORG }}/${{ env.REPO }}\", \"tag\": \"${{ env.TAG }}\"}"

      - name: Update Mainnet Deployment
        run: |-
          curl -v -u "${{ secrets.KEEL_MAINNET_USERNAME }}:${{ secrets.KEEL_MAINNET_PASSWORD }}" -X POST ${{ env.MAINNET_WEBHOOK_ENDPOINT }} -H "Content-Type: application/json" -d "{\"name\": \"${{ env.ORG }}/${{ env.REPO }}\", \"tag\": \"${{ env.TAG }}\"}"
