name: Docker-Production

on:
  push:
    branches:
      - chains/coreum

env:
  REPO: big-dipper-ui
  ORG: coreumfoundation

jobs:
  Build-and-Publish:
    strategy:
      fail-fast: true
      matrix:
        env: [ "devnet", "devnet-2", "znet" ]
        include:
          - env: "devnet"
            NEXT_PUBLIC_GRAPHQL_URL: "https://hasura.devnet-1.coreum.dev/v1/graphql"
            NEXT_PUBLIC_GRAPHQL_WS: "wss://hasura.devnet-1.coreum.dev/v1/graphql"
            NEXT_PUBLIC_URL="https: //explorer.devnet-1.coreum.com"
            NEXT_PUBLIC_RPC_WEBSOCKET: "wss://tendermint-rpc-s-0.devnet-2.coreum.dev/websocket"
            NEXT_PUBLIC_CHAIN_TYPE: "devnet"
            NODE_ENV: "production"
            PORT: "3000"
          - env: "devnet-2"
            NEXT_PUBLIC_GRAPHQL_URL: "https://hasura.devnet-2.coreum.dev/v1/graphql"
            NEXT_PUBLIC_GRAPHQL_WS: "wss://hasura.devnet-2.coreum.dev/v1/graphql"
            NEXT_PUBLIC_URL: "https://explorer.devnet-2.coreum.com"
            NEXT_PUBLIC_RPC_WEBSOCKET: "wss://tendermint-rpc-s-0.devnet-2.coreum.dev/websocket"
            NEXT_PUBLIC_CHAIN_TYPE: "devnet"
            NODE_ENV: "production"
            PORT: "3000"
          - env: "znet"
            NEXT_PUBLIC_GRAPHQL_URL: "http://localhost:8080/v1/graphql"
            NEXT_PUBLIC_GRAPHQL_WS: "ws://localhost:8080/v1/graphql"
            NEXT_PUBLIC_URL: "http://localhost:3030"
            NEXT_PUBLIC_RPC_WEBSOCKET: "ws://localhost:26657/websocket"
            NEXT_PUBLIC_CHAIN_TYPE: "devnet"
            NODE_ENV: "production"
            PORT: "3000"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Env
        run: |
          echo "BUILD_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ${{ env.ORG }}/${{ env.REPO }}:${{ matrix.env }}-${{ env.BUILD_SHA }}
            ${{ env.ORG }}/${{ env.REPO }}:${{ matrix.env }}-latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          push: true
          build-args: |
            "NEXT_PUBLIC_GRAPHQL_URL=${{ matrix.NEXT_PUBLIC_GRAPHQL_URL }}"
            "NEXT_PUBLIC_GRAPHQL_WS=${{ matrix.NEXT_PUBLIC_GRAPHQL_WS }}"
            "NEXT_PUBLIC_URL=${{ matrix.NEXT_PUBLIC_URL }}"
            "NEXT_PUBLIC_RPC_WEBSOCKET=${{ matrix.NEXT_PUBLIC_RPC_WEBSOCKET }}"
            "NEXT_PUBLIC_CHAIN_TYPE=${{ matrix.NEXT_PUBLIC_CHAIN_TYPE }}"
            "NODE_ENV=${{ matrix.NODE_ENV }}"
            "PORT=${{ matrix.PORT }}"
